// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Мефодьев Илья",
            "url": "https://t.me/Thir5tyF0r1ife",
            "email": "creatoreli8@gmail.com"
        },
        "license": {
            "name": "AS IS (NO WARRANTY)"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/armies": {
            "get": {
                "description": "Получить список армий, включая фильтрацию (param \"class\") и поисковый запрос (param \"searchNameArmy\")",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Requests"
                ],
                "summary": "Получить список армий",
                "parameters": [
                    {
                        "type": "string",
                        "description": "фильтрация",
                        "name": "class",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "поиск армии",
                        "name": "searchNameArmy",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/ds.Army"
                            }
                        }
                    }
                }
            }
        },
        "/army": {
            "post": {
                "description": "Создать одну армию",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Requests"
                ],
                "summary": "Создать армию",
                "parameters": [
                    {
                        "description": "данные армии",
                        "name": "army",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ds.Army"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.ArmyResSw"
                        }
                    }
                }
            }
        },
        "/army/add_to_travel": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Добавить армию в расчёт, зная её идентификатор и при необходимости создавая новый черновик",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Requests"
                ],
                "summary": "Добавить армию в расчёт",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID добавляемой армии",
                        "name": "id",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.ResDraftSw"
                        }
                    }
                }
            }
        },
        "/army/{id}": {
            "get": {
                "description": "Получить одну армию по её id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Requests"
                ],
                "summary": "Получить одну армию",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id армии",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ds.Army"
                        }
                    }
                }
            },
            "put": {
                "description": "Изменить одну армию, зная её идентификатор и изменяя существующие поля",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Requests"
                ],
                "summary": "Изменить армию",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID изменяемой армии",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "данные армии",
                        "name": "army",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ds.Army"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.ArmyResSw"
                        }
                    }
                }
            },
            "delete": {
                "description": "Удалить одну армию, зная её идентификатор и изменяя статус (запрещено удалять запись из БД)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Requests"
                ],
                "summary": "Удалить армию",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID удаляемой армии",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.message"
                        }
                    }
                }
            }
        },
        "/army/{id}/upload_image": {
            "post": {
                "description": "Добавить или Обновить изображение армии зная её идентификатор",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Requests"
                ],
                "summary": "Добавить или Обновить изображение армии",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID армии к которой добавляется изображение",
                        "name": "id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Изображение армии",
                        "name": "image_army",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.UploadResponse"
                        }
                    }
                }
            }
        },
        "/historian": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Получить информацию об историке (для его личного кабинета), уже авторизованном",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Requests"
                ],
                "summary": "Получить информацию об историке",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.HisSw"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Обновить информацию об историке по его логину",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Requests"
                ],
                "summary": "Обновить информацию об историке",
                "parameters": [
                    {
                        "type": "string",
                        "description": "логин историка",
                        "name": "LoginHistorian",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "пароль историка",
                        "name": "PasswordHistorian",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "Историк - модератор?",
                        "name": "HisIsModerator",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.HisSw"
                        }
                    }
                }
            }
        },
        "/historian/auth": {
            "post": {
                "description": "Аутентификация историка по его логину и паролю",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Requests"
                ],
                "summary": "Аутентификация историка",
                "parameters": [
                    {
                        "type": "string",
                        "description": "логин историка",
                        "name": "loginHistorian",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "пароль историка",
                        "name": "passwordHistorian",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.MesHisLPMSw"
                        }
                    }
                }
            }
        },
        "/historian/exit": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Деавторизация историка (завершение текущей сессии)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Requests"
                ],
                "summary": "Деавторизация историка",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.message"
                        }
                    }
                }
            }
        },
        "/historian/reg": {
            "post": {
                "description": "Регистрация историка по его логину и паролю",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Requests"
                ],
                "summary": "Регистрация историка",
                "parameters": [
                    {
                        "type": "string",
                        "description": "логин историка",
                        "name": "LoginHistorian",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "пароль историка",
                        "name": "PasswordHistorian",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.MesHisLPMSw"
                        }
                    }
                }
            }
        },
        "/travel_time": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Получить id черновика и количество армий в нём (id вычисляется для текущего пользователя)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Requests"
                ],
                "summary": "Получить id черновика и количество армий в нём",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.idDraftCountArmies"
                        }
                    }
                }
            }
        },
        "/travel_time/delete_army": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Удалить армию из расчёта по id расчёта и id армии",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Requests"
                ],
                "summary": "Удалить армию из расчёта",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id расчёта",
                        "name": "ttid",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "id армии",
                        "name": "ArmyID",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.message"
                        }
                    }
                }
            }
        },
        "/travel_time/update_army": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Обновить летописные сведения (поле M:M) - измерение пройденного за день расстояния по летописи",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Requests"
                ],
                "summary": "Обновить летописные сведения",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id расчёта",
                        "name": "ttid",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "id армии",
                        "name": "ArmyID",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "пройденное расстояние за день по летописи",
                        "name": "newKmPerDayChronical",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.message"
                        }
                    }
                }
            }
        },
        "/travel_time/{ttid}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Получить расчёт по его id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Requests"
                ],
                "summary": "Получить расчёт",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id расчёта",
                        "name": "ttid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.ttToresultsStrPlusArmies"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Обновить расчёт по его id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Requests"
                ],
                "summary": "Обновить расчёт",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id расчёта",
                        "name": "ttid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Обновленные данные расчёта",
                        "name": "TimeToAdd",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ds.TravelTime"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ds.TravelTime"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Удалить расчёт по его id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Requests"
                ],
                "summary": "Удалить расчёт",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id расчёта",
                        "name": "ttid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.message"
                        }
                    }
                }
            }
        },
        "/travel_time/{ttid}/form": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Сформировать расчёт по его id, происходит проверка на обязательные поля",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Requests"
                ],
                "summary": "Сформировать расчёт",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id расчёта",
                        "name": "ttid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ds.TravelTime"
                        }
                    }
                }
            }
        },
        "/travel_time/{ttid}/moderate": {
            "put": {
                "description": "Завершить/отклонить расчёт по его id, происходит расчёт и оценка времени, требуемого на переход заданной дистанции",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Requests"
                ],
                "summary": "Завершить/отклонить расчёт",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id расчёта",
                        "name": "ttid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "завершить",
                            "отклонить"
                        ],
                        "type": "string",
                        "description": "Выбор действия (завершить или отклонить)",
                        "name": "statusTT",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.TTplusMessage"
                        }
                    }
                }
            }
        },
        "/travel_times": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Получить список Расчётов, включая фильтрацию по диапазону дат и статусу",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Requests"
                ],
                "summary": "Получить список Расчётов",
                "parameters": [
                    {
                        "type": "string",
                        "format": "date",
                        "description": "фильтр даты начала",
                        "name": "dateFromTT",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "format": "date",
                        "description": "фильтр даты окончания",
                        "name": "dateToTT",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "статус расчёта",
                        "name": "statusTT",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/ds.TravelTime"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "ds.Army": {
            "type": "object",
            "properties": {
                "ArmyID": {
                    "type": "integer"
                },
                "ClassArmy": {
                    "description": "для фильтрации",
                    "type": "string"
                },
                "DescriptionArmy": {
                    "type": "string"
                },
                "ImageArmyUrl": {
                    "type": "string"
                },
                "MaxDesertSpeed": {
                    "description": "Пустыня Максимальная",
                    "type": "integer"
                },
                "MaxForestSpeed": {
                    "description": "Лес Максимальная",
                    "type": "integer"
                },
                "MaxMountSpeed": {
                    "description": "Горы Максимальная",
                    "type": "integer"
                },
                "MaxPlainSpeed": {
                    "description": "Равнина Максимальная",
                    "type": "integer"
                },
                "MaxRiverSpeed": {
                    "description": "Река Максимальная",
                    "type": "integer"
                },
                "MinDesertSpeed": {
                    "description": "Пустыня минимальная",
                    "type": "integer"
                },
                "MinForestSpeed": {
                    "description": "Лес минимальная",
                    "type": "integer"
                },
                "MinMountSpeed": {
                    "description": "Горы минимальная",
                    "type": "integer"
                },
                "MinPlainSpeed": {
                    "description": "скорости для каждого типа местности:",
                    "type": "integer"
                },
                "MinRiverSpeed": {
                    "description": "Река минимальная",
                    "type": "integer"
                },
                "NameArmy": {
                    "type": "string"
                },
                "StatusArmy": {
                    "description": "status: удален/действует",
                    "type": "string"
                }
            }
        },
        "ds.Historian": {
            "type": "object",
            "properties": {
                "historianUUID": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "login": {
                    "type": "string"
                },
                "role": {
                    "description": "HisIsModerator bool      ` + "`" + `gorm:\"type:boolean;default:false\" json:\"is_moderator\"` + "`" + `",
                    "allOf": [
                        {
                            "$ref": "#/definitions/role.Role"
                        }
                    ]
                }
            }
        },
        "ds.TravelTime": {
            "type": "object",
            "properties": {
                "ChosenBiomTT": {
                    "description": "\"Desert\", \"Plain\", \"Mount\", \"Forest\", \"River\"",
                    "type": "string"
                },
                "DistanceTT": {
                    "type": "integer"
                },
                "ResultChronical": {
                    "type": "integer"
                },
                "ResultMaxTT": {
                    "type": "integer"
                },
                "ResultMinTT": {
                    "type": "integer"
                },
                "StatusTT": {
                    "description": "5 статусов: черновик, удален, сформирован, завершен, отклонен",
                    "type": "string"
                },
                "creatorID_TT": {
                    "type": "integer"
                },
                "creatorTT": {
                    "$ref": "#/definitions/ds.Historian"
                },
                "dateCreateTT": {
                    "type": "string"
                },
                "dateFinishTT": {
                    "type": "string"
                },
                "dateUpdateTT": {
                    "type": "string"
                },
                "moderatorID_TT": {
                    "type": "integer"
                },
                "moderatorTT": {
                    "$ref": "#/definitions/ds.Historian"
                },
                "ttID": {
                    "type": "integer"
                }
            }
        },
        "handler.ArmyResSw": {
            "type": "object",
            "properties": {
                "army": {
                    "$ref": "#/definitions/ds.Army"
                }
            }
        },
        "handler.HisSw": {
            "type": "object",
            "properties": {
                "historian": {
                    "$ref": "#/definitions/ds.Historian"
                }
            }
        },
        "handler.MesHisLPMSw": {
            "type": "object",
            "properties": {
                "historian": {
                    "$ref": "#/definitions/ds.Historian"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "handler.ResDraftSw": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "travel_time": {
                    "$ref": "#/definitions/ds.TravelTime"
                }
            }
        },
        "handler.TTplusMessage": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "travel_time": {
                    "$ref": "#/definitions/ds.TravelTime"
                }
            }
        },
        "handler.UploadResponse": {
            "type": "object",
            "properties": {
                "file_name": {
                    "type": "string"
                },
                "file_size": {
                    "type": "integer"
                },
                "file_url": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "handler.idDraftCountArmies": {
            "type": "object",
            "properties": {
                "countArmies": {
                    "type": "integer"
                },
                "ttid": {
                    "type": "integer"
                }
            }
        },
        "handler.message": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "handler.resultsStr": {
            "type": "object",
            "properties": {
                "chosenBiomTT": {
                    "type": "string"
                },
                "creatorLogin": {
                    "type": "string"
                },
                "dateCreateTT": {
                    "type": "string"
                },
                "dateFinishTT": {
                    "type": "string"
                },
                "dateUpdateTT": {
                    "type": "string"
                },
                "distanceTT": {
                    "type": "integer"
                },
                "moderatorLogin": {
                    "type": "string"
                },
                "resultChronical": {
                    "type": "integer"
                },
                "resultMaxTT": {
                    "type": "integer"
                },
                "resultMinTT": {
                    "type": "integer"
                },
                "statusTT": {
                    "description": "5 статусов: черновик, удален, сформирован, завершен, отклонен",
                    "type": "string"
                },
                "ttID": {
                    "type": "integer"
                }
            }
        },
        "handler.ttToresultsStrPlusArmies": {
            "type": "object",
            "properties": {
                "list_armies": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ds.Army"
                    }
                },
                "time_travel": {
                    "$ref": "#/definitions/handler.resultsStr"
                }
            }
        },
        "role.Role": {
            "type": "integer",
            "enum": [
                0,
                1
            ],
            "x-enum-comments": {
                "Historian": "0",
                "Moderator": "1"
            },
            "x-enum-descriptions": [
                "0",
                "1"
            ],
            "x-enum-varnames": [
                "Historian",
                "Moderator"
            ]
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Введите: Bearer {ваш_JWT_токен}",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8084",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Travel Times API",
	Description:      "Система расчёта дневного перехода армии",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
